### ISSUE TITLE
Non 120 and No Nazj Entry.. ATT does it...

### ISSUE THREAD

**Issue by vandiel01** [DrOxlotus/LastSeen#10]
ODDDD thing, i DONT even have the item AND im not even 120 AND im not in Nazj but mousing over or clicking on ATT will give me

![image](https://user-images.githubusercontent.com/52209920/61059032-f53be380-a3bd-11e9-89b9-d5a1e37c71be.png)

**Comment by DrOxlotus** [comment]
This is a report for the wrong project. Please post an issue on the [Curator](https://github.com/DrOxlotus/Curator/issues) issues page.
