### ISSUE TITLE
Error in Garrison Mine - looting primal spirit?

### ISSUE THREAD

**Issue by Resika0904** [DrOxlotus/LastSeen#20]
popped up when looting primal spirit in garrison mine. unsure if from the addon directly or if there is a clash somewhere.

Date: 2019-08-27 08:14:59
ID: 22
Error occured in: Global
Count: 1
Message: ..\AddOns\LastSeen\Functions\ItemHandler.lua line 146:
attempt to compare nil with number
Debug:
LastSeen\Functions\ItemHandler.lua:146:
LastSeen\Functions\ItemHandler.lua:138
LastSeen\Functions\ItemHandler.lua:224: LootDetected()
LastSeen\Init.lua:55:
LastSeen\Init.lua:51
LastSeen\Init.lua:188:
LastSeen\Init.lua:89
Locals:
itemLink = "[Primal Spirit]"
currentDate = "08/27/19"
currentMap = "Lunarfall"
itemID = 120945
itemName = "Primal Spirit"
itemRarity = 2
itemType = "Tradeskill"
(*temporary) = nil
(*temporary) = "Tradeskill"
(*temporary) = 6
(*temporary) = "Primal Spirit"
(*temporary) = "[Primal Spirit]"
(*temporary) = 2
(*temporary) = 100
(*temporary) = 0
(*temporary) = "Tradeskill"
(*temporary) = "Elemental"
(*temporary) = 1000
(*temporary) = ""
(*temporary) = "attempt to compare nil with number"
GetItemIDFromItemLink = <function> defined @Interface\AddOns\LastSeen\Functions\ItemHandler.lua:83
GetItemNameFromItemID = <function> defined @Interface\AddOns\LastSeen\Functions\ItemHandler.lua:89
GetItemRarityFromItemID = <function> defined @Interface\AddOns\LastSeen\Functions\ItemHandler.lua:95
GetItemTypeFromItemID = <function> defined @Interface\AddOns\LastSeen\Functions\ItemHandler.lua:101
LastSeenTbl = <table> {
currentMap = "Lunarfall"
AddCreatureByNameplate = <function> defined @Interface\AddOns\LastSeen\Functions\NameplateHandler.lua:64
LogQuestLocation = <function> defined @Interface\AddOns\LastSeen\Functions\QuestHandler.lua:18
LoadSettings = <function> defined @Interface\AddOns\LastSeen\General\Settings.lua:616
isMailboxOpen = false
lootedObject = ""
GetItemsSeen = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:338
lootedItem = ""
target = "Mine Cart"
ignoredItemTypes = <table> {
}
DataIsValid = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:223
New = <function> defined @Interface\AddOns\LastSeen\Functions\ItemHandler.lua:16
tab2 = <unnamed> {
}
tab3 = <unnamed> {
}
itemType = ""
tab1 = <unnamed> {
}
rareSoundID = 567437
rarity = 2
mode = "Normal"
IfExists = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:305
ShouldItemBeIgnored = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:345
removedItems = <table> {
}
Search = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:85
GenerateItemKey = <function> defined @Interface\AddOns\LastSeen\Functions\ItemHandler.lua:200
Round = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:315
playerLootedObject = true
ExtractItemLink = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:287
isQuestReward = false
itemName = ""
mapID = 0
lootControl = false
GetItemStatus = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:208
ignoredItems = <table> {
}
itemLooted = ""
Update = <function> defined @Interface\AddOns\LastSeen\Functions\ItemHandler.lua:36
GetCurrentMap = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:190
itemID = 0
Remove = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:71
Add = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:33
query = ""
TableHasField = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:326
L = <table> {
}
lootedCreatureID = 0
isAutoLootPlusLoaded = false
OnTooltipSetItem = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:240
itemsToSource = <table> {
}
AddCreatureByMouseover = <function> defined @Interface\AddOns\LastSeen\Functions\NameplateHandler.lua:37
doNotIgnore = false
doNotPlayRareSound = false
spells = <table> {
}
wasLootedFromItem = false
Ignore = <function> defined @Interface\AddOns\LastSeen\Functions\FunctionHandler.lua:52
isInInstance = false
QuestChoices = <function> defined @Interface\AddOns\LastSeen\Functions\QuestHandler.lua:33
doNotUpdate = false
LootDetected = <function> defined @Interface\AddOns\LastSeen\Functions\ItemHandler.lua:204
LastSeenPlayers = <table> {
}
isAuctionItem = false
itemRarity = 0
wasUpdated = false
}
L = <table> {
IS_VEHICLE = "Vehicle"
MAIL = "Mail"
VANDIEL = "Without Vandiel, not as many bugs or quirks
AddOns:
Swatter, v8.2.6377 (SwimmingSeadragon)
WowheadLooter, v80200
acbCastBar, v18.08.20
acbMirror, v18.08.12
Ace3, v
AckisRecipeList, v8.2.0.2
ACP, vr259 
AllTheThings, v1.9.8a
Altoholic, vr191
Armory, vv15.4.1
ArmoryGuildBank, vv15.4.1
Atlas, vv1.44.06
AtlasBattlegrounds, vv1.44.01
AtlasBurningCrusade, vv1.44.01
AtlasCataclysm, vv1.44.01
AtlasClassicWoW, vv1.44.01
AtlasClassOrderHalls, vv1.44.01
AtlasDungeonLocs, vv1.44.01
AtlasLegion, vv1.44.01
AtlasMistsofPandaria, vv1.44.01
AtlasOutdoorRaids, vv1.44.01
AtlasScenarios, vv1.44.00
AtlasTransportation, vv1.44.01
AtlasWarlordsofDraenor, vv1.44.01
AtlasWrathoftheLichKing, vv1.44.01
AtlasLoot, vv8.10.00
AtlasLootBattleforAzeroth, vv8.10.00
AtlasLootBurningCrusade, vv8.10.00
AtlasLootCataclysm, vv8.10.00
AtlasLootClassic, vv8.10.00
AtlasLootLegion, vv8.10.00
AtlasLootMistsofPandaria, vv8.10.00
AtlasLootSource, vv0.3
AtlasLootWarlordsofDraenor, vv8.10.00
AtlasLootWrathoftheLichKing, vv8.10.00
AucAdvanced, v8.2.6338 (SwimmingSeadragon)
AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
AucScanData, v8.2.6365 (SwimmingSeadragon)
AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
AucStatSimple, v8.2.6368 (SwimmingSeadragon)
AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
AzCastBar, v18.08.20
Bagnon, v8.2.0
BagnonConfig, v8.2.0
BagnonFacade, v8.2.0
Bartender4, v4.8.4
Bartender4ThereIsNoCost, v
BattlePetBreedID, vr199
ButtonFacade, v4.0.340
ButtonFacadeNotCaith, v3.0.50
caelLib, v
caelMedia, v
caelNameplates, v
CanIMogIt, v8.2.0v1.15
Carbonite, vv8.2.0
CarboniteQuests, vv8.2.0
ClassTimer, v2.3.80000.1
Collectinator, v8.2.0.1
CurrencyTracker, v1.4
CurseProfiler, v
DataStore, vr66
DataStoreAchievements, vr48
DataStoreAgenda, vr30
DataStoreAuctions, vr51
DataStoreCharacters, vr44
DataStoreContainers, vr60
DataStoreCrafts, vr83
DataStoreCurrencies, vr39
DataStoreGarrisons, vr25
DataStoreInventory, vr54
DataStoreMails, vr53
DataStorePets, vr45
DataStoreQuests, vr47
DataStoreReputations, vr44
DataStoreSpells, vr33
DataStoreStats, vr32
DataStoreTalents, vr62
DBMCore, v8.2.15
DBMDefaultSkin, v
DBMSpellTimers, v
DBMStatusBarTimers, v
dMinimap, v
Enchantrix, v8.2.6373 (SwimmingSeadragon)
ExecutiveAssistant, v1.3a
ExecutiveAssistantlibExecAssistExample, v1.13
ExecutiveAssistantQuestIntern, v1.0.1c
ForteCasting, v
ForteClass, v
ForteCooldown, v
ForteCore, v1.980.8
ForteHealthstone, v
ForteSoulstone, v
ForteSummon, v
ForteTimer, v
Gatherer, v7.3.1
GTFO, v4.48.10
Informant, v8.2.6374 (SwimmingSeadragon)
ItemDataCache, v1.505
kgPanels, v1.21
LastSeen, v11.4.0
LegionWardrobe, v30
LegionWardrobeData, v
LibAboutPanel, vv1.52
LibSharedMedia30, v3.0-112
LockedOut, v1.10.5
Masque, v8.0.1
MasqueCaith, v8.0.0
MikScrollingBattleText, v5.7.150
MinimapButtonFrame, v3.1.10h
MinimapButtonFrameSkinPack, v3.0.1b
MoveAnything, v17.0.5
MSBTSharedMedia, v1.3
NPCScan, v8.0.1.13
NugComboBar, v8.2.1
NugComboBarGUI, v
Omen, v3.2.2
PhanxChat, v8.0.0.1
Postal, vv3.6.0
PowerAuras, v4.30.2
QuestCompletist, v109.24
Rarity, v1.0 (r691-release)
RarityOptions, v
Raven, v
Recount, vv8.2.0b
Reflux, v1.17
RepHelper, v8.2.0.2-release
SharedMedia, v3.1.0-191
SLDataText, v8.0.2
SlideBar, v8.2.6375 (SwimmingSeadragon)
Stubby, v8.2.6376 (SwimmingSeadragon)
Stuf, v8.0.001
TidyPlates, v6.19.3
TidyPlatesGraphite, v
TidyPlatesGrey, v
TidyPlatesNeon, v
TidyPlatesQuatre, v
TidyPlatesSimple, v8.0
TidyPlatesThreatPlates, v9.1.12
TidyPlatesHub, v
TidyPlatesWidgets, v
Titan, v5.18.2.80200
TitanArchaeology, v1.0.2
TitanBag, v5.18.2.80200
TitanClock, v5.18.2.80200
TitanGold, v5.18.2.80200
TitanLocation, v5.18.2.80200
TitanLootType, v5.18.2.80200
TitanPerformance, v5.18.2.80200
TitanRepair, v5.18.2.80200
TitanReputation, v3.9.5
TitanVolume, v5.18.2.80200
TitanXP, v5.18.2.80200
VuhDo, v3.107
VuhDoOptions, v3.107
WakeSpams, v2.1.82-release
WakeSpamsOptions, v2.1.82-release
WardrobeTracker, v1.0.1
WoWDBProfiler, v
WowheadGarrisonTimer, v1.0.9
xDamageFont, v20200
BlizRuntimeLib_enUS v8.2.0.80200 <none>
(ck=112c)

**Comment by DrOxlotus** [comment]
Fixed in **Patch 1.0.1.0**, due for release by October 15th.
