### ISSUE TITLE
List of Chest :( (will continue to grow if I find more)

### ISSUE THREAD

**Issue by vandiel01** [DrOxlotus/LastSeen#21]
It last recorded in June, today (Aug 31) went back to ToC (Raid) and this time, didn't record anything from the chest (During Champion of the Horde phase).

![image](https://user-images.githubusercontent.com/52209920/64071138-01635500-cc39-11e9-9538-51015c446338.png)

Edit 1: Ran ToC Dungeon, the chest also count for some items, not all

Edit 2: All Chests in Ulduar doesn't count/update/add

Edit 3: 4 Horsemen Chest in Naxx doesn't count/update/add some items

Edit 4: All Chest in ICC doesn't count/update/add some items

**Comment by DrOxlotus** [comment]
There should be a _fix_ available for testing on the **staging** branch.

**Comment by DrOxlotus** [comment]
Fixed on 67cdbc5.
