### ISSUE TITLE
As Project Lead, I would like to fix loot tracking from all objects

### ISSUE THREAD

**Issue by DrOxlotus** [DrOxlotus/LastSeen#32]

**Comment by DrOxlotus** [comment]
https://github.com/DrOxlotus/LastSeen/issues/28

**Comment by Beornwulf** [comment]
As requested in Discord, screenshot of error message about Miner's Coffee from cart in the alliance mine. It looks like it's only some carts, this one was at 61.20 25.20.
![image](https://user-images.githubusercontent.com/5617122/67385985-0df69080-f58c-11e9-9f3b-911f25ec1672.png)

**Comment by DrOxlotus** [comment]
Scout's Belongings is a bit tricky, as it triggers several events that handle objects. I'm trying to reign in control by handling objects with fewer events.

**Comment by DrOxlotus** [comment]
I found the problem.

**Comment by DrOxlotus** [comment]
These should all be fixed.
