### ISSUE TITLE
Rep Quest Reward

### ISSUE THREAD

**Issue by vandiel01** [DrOxlotus/LastSeen#34]
Got this error when I selected an quest chest from the rep vendor (Eldara Dawnrunner @ 47.2 30.7) in Isle of Quel'Danas when i 'ding' a rep (honored, revered)

1x LastSeen\Init.lua:292: attempt to index field '?' (a nil value)
LastSeen\Init.lua:292: in function <LastSeen\Init.lua:89>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "QUEST_LOOT_RECEIVED"
(*temporary) = <function> defined @LastSeen\Functions\ItemHandler.lua:230
(*temporary) = "You receive item: |cffffffff|Hitem:34592::::::::113:70::11::::|h[Aldor Supplies Package]|h|r"
(*temporary) = "10/18/2019"
(*temporary) = nil
(*temporary) = 11556
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
EmptyVariables = <function> defined @LastSeen\Init.lua:63
isLastSeenLoaded = true
GenerateNewKey = <function> defined @LastSeen\Init.lua:26
InitializeTable = <function> defined @LastSeen\Init.lua:21
LastSeenTbl = <table> {
 AddCreatureByNameplate = <function> defined @LastSeen\Functions\NameplateHandler.lua:72
 rank_common = 9999
 LogQuestLocation = <function> defined @LastSeen\Functions\QuestHandler.lua:18
 LoadSettings = <function> defined @LastSeen\General\Settings.lua:568
 GetItemsSeen = <function> defined @LastSeen\Functions\FunctionHandler.lua:347
 lootedItem = ""
 target = ""
 ignoredItemTypes = <table> {
 }
 rarity = 2
 IfExists = <function> defined @LastSeen\Functions\FunctionHandler.lua:314
 rareIcon = "|T134563:12|t "
 removedItems = <table> {
 }
 Search = <function> defined @LastSeen\Functions\FunctionHandler.lua:87
 playerLootedObject = false
 GenerateItemKey = <function> defined @LastSeen\Functions\ItemHandler.lua:226
 itemName = ""
 Update = <function> defined @LastSeen\Functions\ItemHandler.lua:50
 TableHasField = <function> defined @LastSeen\Functions\FunctionHandler.lua:335
 mode = "Normal"
 rank_legendary = 49999
 OnTooltipSetItem = <function> defined @LastSeen\Functions\FunctionHandler.lua:242
 itemsToSource = <table> {
 }
 badDataIcon = "|T133730:12|t "
 isInInstance = false
 QuestChoices = <function> defined @LastSeen\Functions\QuestHandler.lua:37
 doNotUpdate = false
 ExtractItemLink = <function> defined @LastSeen\Functions\FunctionHandler.lua:296
 LastSeenPlayers = <table> {
 }
 commonIcon = "|T133787:12|t "
 doNotIgnore = false
 rank_artifact = 50000
 rank_epic = 29999
 legendaryIcon = "|T133066:12|t "
 isAutoLootPlusLoaded = false
 lootedObject = ""
 rank_poor = 4999
 New = <function> defined @LastSeen\Functions\ItemHandler.lua:17
 itemType = ""
 tab1 = <table> {
 }
 currentMap = "Isle of Quel'Danas"
 rareSoundID = 567437
 autoMark = false
 GetItemStatus = <function> defined @LastSeen\Functions\FunctionHandler.lua:210
 rank_uncommon = 14999
 Add = <function> defined @LastSeen\Functions\FunctionHandler.lua:31
 encounterName = ""
 doNotPlayRareSound = true
 uncommonIcon = "|T237281:12|t "
 ShouldItemBeIgnored = <function> defined @LastSeen\Functions\FunctionHandler.lua:377
 ignoredItems = <table> {
 }
 itemLooted = ""
 GetPlayerRank = <function> defined @LastSeen\Functions\FunctionHandler.lua:354
 Round = <function> defined @LastSeen\Functions\FunctionHandler.lua:324
 Remove = <function> defined @LastSeen\Functions\FunctionHandler.lua:69
 artifactIcon = "|T1029580:12|t "
 query = ""
 isMailboxOpen = false
 L = <table> {
 }
 lootedCreatureID = 0
 isAuctionItem = false
 DataIsValid = <function> defined @LastSeen\Functions\FunctionHandler.lua:225
 GetCurrentMap = <function> defined @Interf

**Comment by DrOxlotus** [comment]
This is because the player never actually accepts this quest so its location isn't detected.

**Comment by DrOxlotus** [comment]
I'm experimenting with a fix. (This is the same problem for candy buckets.)

**Comment by DrOxlotus** [comment]
Fixed in previous release.
