### ISSUE TITLE
Drop By Issue (Staging)

### ISSUE THREAD

**Issue by vandiel01** [DrOxlotus/LastSeen#4]
![image](https://user-images.githubusercontent.com/52209920/60301026-fff27500-98f5-11e9-9772-849081c927f8.png)

drop from first boss in BWL but "drop by" something else (Angler's Water Strider in bag)

**Comment by DrOxlotus** [comment]
This is in progress. I'm conducting tests, but this shouldn't be a problem moving forward.

**Comment by DrOxlotus** [comment]
I haven't seen this pop up again in some time.

**Comment by DrOxlotus** [comment]
Fixed in latest release.
