### ISSUE TITLE
Bug when opening mail.

### ISSUE THREAD

**Issue by DiscordGregory** [DrOxlotus/LastSeen#56]
Didn't do anything special, logged in and got the error when I opened the mailbox. The item is a drop from a Timewalking dungeon I didn't loot. I'm using the twitch release if that matters.

2x LastSeen\Main.lua:307: attempt to compare number with nil
[string "@LastSeen\Main.lua"]:307: in function <LastSeen\Main.lua:72>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "MAIL_INBOX_UPDATE"
mailItems = 1
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
_ = 960784
_ = 134327
sender = "The Postmaster"
subject = "Recovered Item"
(for index) = 1
(for limit) = 16
(for step) = 1
j = 1
(*temporary) = nil
(*temporary) = 2
(*temporary) = <function> defined =[C]:-1
(*temporary) = "|cffffffff|Hitem:109879::::::::120:252:512:22:2:6424:6652:120:::|h[]|h|r"
(*temporary) = 960784
(*temporary) = "INVTYPE_WRIST"
(*temporary) = 960784
(*temporary) = 4
(*temporary) = 4
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
addonTbl = <table> {
 doNotIgnore = false
 AddCreatureByNameplate = <function> defined @LastSeen\Handlers\NameplateHandler.lua:27
 LoadSettings = <function> defined @LastSeen\Settings.lua:138
 isAutoLootPlusLoaded = false
 ignoredItemCategories = <table> {
 }
 AddQuest = <function> defined @LastSeen\Handlers\QuestHandler.lua:12
 New = <function> defined @LastSeen\Handlers\ItemHandler.lua:10
 GetQuestInfo = <function> defined @LastSeen\Handlers\QuestHandler.lua:23
 GetTable = <function> defined @LastSeen\Handlers\FunctionHandler.lua:280
 questID = 0
 maxHistoryEntries = 20
 removedItems = <table> {
 }
 Search = <function> defined @LastSeen\Handlers\FunctionHandler.lua:55
 Contains = <function> defined @LastSeen\Handlers\FunctionHandler.lua:253
 wasUpdated = false
 itemSourceCreatureID = 0
 ignoredItems = <table> {
 }
 Update = <function> defined @LastSeen\Handlers\ItemHandler.lua:52
 isFasterLootLoaded = false
 Remove = <function> defined @LastSeen\Handlers\FunctionHandler.lua:23
 query = ""
 lootFast = false
 L = <table> {
 }
 GetCurrentMap = <function> defined @LastSeen\Handlers\FunctionHandler.lua:148
 rarity = 2
 OnTooltipSetItem = <function> defined @LastSeen\Handlers\FunctionHandler.lua:189
 itemsToSource = <table> {
 }
 AddCreatureByMouseover = <function> defined @LastSeen\Handlers\NameplateHandler.lua:6
 mode = "Debug"
 DataIsValid = <function> defined @LastSeen\Handlers\FunctionHandler.lua:168
 RollHistory = <function> defined @LastSeen\Handlers\FunctionHandler.lua:289
 GetTableKeyFromValue = <function> defined @LastSeen\Handlers\FunctionHandler.lua:243
 GetItemInfo = <function> defined @LastSeen\Handlers\FunctionHandler.lua:301
 isInInstance = false
 currentMap = "Warspear"
 events = <table> {
 }
 ExtractItemLink = <function> defined @LastSeen\Handlers\FunctionHandler.lua:223
 GetCount = <function> defined @LastSeen\Handlers\FunctionHandler.lua:6
 isLastSeenLoaded = true
 AddItem = <function> defined @LastSeen\Handlers\ItemHandler.lua:132
 doNotUpdate = false
}
InitializeTable = <function> defined @LastSeen\Main.lua:37
playerName = "Brando"
L = <table> {
 DATE = "06/13/2020"
 INFO_MSG_IGNORED_ITEM = "This item is automatically ignored."
 CMD_LOOT = "loot"
 ERROR_MSG_CANT_COMPLETE_REQUEST = "Can't complete request: "
 ADDON_NAME_SETTINGS = "|cff00ccffLastSeen|r"
 SEARCH_OPTION_I = "i"
 AUCTION_HOUSE = "Auction House"
 CMD_DISCORD = "discord"
 CMD_HISTORY = "history"
 ADDON_NAME = "|cff00ccffLastSeen|r: "
 DEBUG_MODE = "Debug"
 INFO_MSG_ITEM_ADDED = " successfully added."
 AUCTION_WON_SUBJECT = "Auction won:"
 SEARCH_OPTION_C = "c"
 RELEASE = "[2.0] "
 CMD_REMOVE_SHORT = "rm"
 ERROR_MSG_BAD_REQUEST = "Bad request. Please try again."
 LOOT_ITEM_SELF = "You receive loot: "
 INFO_MSG_POSTMASTER = "The Postmaster"
 QUIET_MODE_DESC = "No output!
"
 CMD_REMOVE = "remove"
 INFO_MSG_LOOT_ENABLED = "Loot Fast mode enabled."
 NORMAL_MODE_DESC = "Shows new and updated items.
"
 CMD_VIEW = "view"
 QUIET_MODE = "Quiet"
 IS_UNKNOWN = "Unknown"
 CMD_IMPORT = "import"
 ERROR_MSG_CANT_ADD = "Can't add specif

**Comment by DrOxlotus** [comment]
There will be a check in place in 2.1 that will hold items with bad rarity in the mailbox.

**Comment by DrOxlotus** [comment]
If the player doesn't auto loot the items from the mailbox, then they can close and reopen it to try again.
