### ISSUE TITLE
AH items with "flavors" are not deduped

### ISSUE THREAD

**Issue by Arcanemagus** [DrOxlotus/LastSeen#6]
When looting items with "flavors" such as `Wavecrash Greaves of the Quickblade` LastSeen is currently saving them as the specific variant, instead of the family as a whole:
![image](https://user-images.githubusercontent.com/427137/60401659-c6aa4700-9b39-11e9-8860-2a05c85dc424.png)

Result:
![image](https://user-images.githubusercontent.com/427137/60401677-0113e400-9b3a-11e9-9b20-b77a163c5a7d.png)
![image](https://user-images.githubusercontent.com/427137/60401664-d9bd1700-9b39-11e9-984e-f682760aef2c.png)

Version: https://github.com/DrOxlotus/LastSeen/commit/1877110da5301e5c4bf0b526a0860145b3a1c5c0

**Comment by DrOxlotus** [comment]
Fixed in 49649e7.
