### ISSUE TITLE
Suggestion (Screen Print Count for New)

### ISSUE THREAD

**Issue by vandiel01** [DrOxlotus/LastSeen#7]
UIErrorsFrame:AddMessage(L["ITEMS_SEEN"] .. lastSeenNS.GetItemsSeen(LastSeenItemsDB), 1.0, 0.5, 0.0, 30);

Add this line or something better, after line 23 below print in "Function\ItemHandler.lua"

Whenever you loot something new, it would print "error msg" on screen for counts

**Comment by DrOxlotus** [comment]
You want the option to see the item count for each new item that you loot? Am I understanding the request properly? @vandiel01

**Comment by vandiel01** [comment]
Yeah on screen as I loot new items :)

**Comment by DrOxlotus** [comment]
Gotcha. I thought so.

**Comment by DrOxlotus** [comment]
Added in d724b1f.
