### ISSUE TITLE
Debugging in lastest release

### ISSUE THREAD

**Issue by Lucetia** [DrOxlotus/LastSeen#78]
Looks like the version on Curse has some internal debugging still turned on.   Get this whenever I hover items anywhere:

> [07:39:38 AM] Consumable 
> [07:39:38 AM] Gem 
> [07:39:38 AM] INVTYPE_BAG 
> [07:39:38 AM] Item Enhancement 
> [07:39:38 AM] Junk 
> [07:39:38 AM] Key 
> [07:39:38 AM] Reagent 
> [07:39:38 AM] Tradeskill 
> [07:39:38 AM] Consumable 
> [07:39:38 AM] Gem 
> [07:39:38 AM] INVTYPE_BAG 
> [07:39:38 AM] Item Enhancement 
> [07:39:38 AM] Junk 
> [07:39:38 AM] Key 
> [07:39:38 AM] Reagent 
> [07:39:38 AM] Tradeskill 

Here are the settings I have because I thought at first maybe I turned on debugging.

![image](https://user-images.githubusercontent.com/36181235/96145347-f5c50300-0eb9-11eb-946d-948113437797.png)

**Comment by DrOxlotus** [comment]
Thank you. This is fixed in 9af7137645ced73f089fb6fd90381ddd3c6708a0.
