### ISSUE TITLE
Tooltip Handler compare with nil

### ISSUE THREAD

**Issue by Lucetia** [DrOxlotus/LastSeen#79]
Been getting this error when hovering over various items in the bag.  Doesn't seem to be the same item each time either.

First time today was when I hovered "Honorbound Legion Scouting Map" but when I hovered it on my alt it didn't have any issues.  It triggered when I hit "Cloudstriker Cord" despite hovering the map first and going through each item one by one.

> 3x LastSeen\handlers\TooltipHandler.lua:33: attempt to compare number with nil
> [string "@LastSeen\handlers\TooltipHandler.lua"]:33: in function <LastSeen\handlers\TooltipHandler.lua:4>
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "=[C]"]: in function `SetBagItem'
> [string "@FrameXML\ContainerFrame.lua"]:1321: in function `ContainerFrameItemButton_OnUpdate'
> [string "@FrameXML\ContainerFrame.lua"]:1368: in function `ContainerFrameItemButton_OnEnter'
> [string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>
> 
> Locals:
> tooltip = GameTooltip {
>  BottomLeftCorner = <unnamed> {
>  }
>  OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
>  GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
>  SetHyperlink = <function> defined =[C]:-1
>  RightEdge = <unnamed> {
>  }
>  ClearBackdrop = <function> define

**Comment by DrOxlotus** [comment]
Should be fixed in the latest release that I just pushed.

**Comment by DrOxlotus** [comment]
If not, ping me on Discord and I'll reopen this ticket.
