### ISSUE TITLE
Quest & Bling 6k

### ISSUE THREAD

**Issue by vandiel01** [DrOxlotus/LastSeen#9]
1x LastSeen\Functions\QuestHandler.lua:62: attempt to concatenate local 'questTitle' (a nil value)
LastSeen\Functions\QuestHandler.lua:62: in function `QuestChoices'
LastSeen\Functions\ItemHandler.lua:199: in function `LootDetected'
LastSeen\Init.lua:244: in function <LastSeen\Init.lua:108>

Locals:
questID = 40753
itemLink = "|cff1eff00|Hitem:132892::::::::120:258::::::|h[Blingtron 6000 Gift Package]|h|r"
today = "07/10/19"
questTitle = nil

**Comment by DrOxlotus** [comment]
A nil quest title. What an interesting problem. I'll test when I next see a Blingtron 6000.

**Comment by DrOxlotus** [comment]
When both quest links and quest titles are unavailable, then we simply use "Quest". Addressed in 81e34b6.
